package fruit.farm.management.entity;

public enum PlantType {
    JABŁOŃ(AppleVariety.class),
    GRUSZA(PearVariety.class),
    WIŚNIA(CherryVariety.class),
    ŚLIWA(PlumVariety.class),
    MALINA(RaspberryVariety.class),
    CZEREŚNIA(SweetCherryVariety.class),

    TRUSKAWKA(StrawberryVariety.class),
    PORZECZKA_CZARNA(BlackCurrantVariety.class),
    PORZECZKA_CZERWONA(RedCurrantVariety.class),
    AGREST(GooseberryVariety.class),
    BORÓWKA(BlueberryVariety.class),
    JEŻYNA(BlackberryVariety.class),
    ARONIA(AroniaVariety.class);

    private final Class<? extends Enum<?>> varietyClass;

    PlantType(Class<? extends Enum<?>> varietyClass) {
        this.varietyClass = varietyClass;
    }

    public enum AppleVariety {
        GOLDEN_DELICIOUS, RED_DELICIOUS, GALA, FUJI, PINK_LADY, BRAEBURN, JONAGOLD,
        GRANNY_SMITH, HONEYCRISP, AMBROSIA, IDARED, LIGOL, SZAMPION, JONATHAN, KOSZTELA,
        MALINOWKA, RENETA, ANANAS_BERENDA, PIROS, GLUCZOWKA, KROLOWA_RENET, CORTLAND,
        MCINTOSH, BOSKOOP, ELSTAR, RUBIN, PAULARED, LOBO, PINOVA, TOPAZ, MODI, JAZZ,
        ENVY, KANZI, RUBYFROST, PRINCE, GLOSTER, MUTSU, ALWA, MELODIA, GALMAC, PAPIEROWKA,
        OLIWKA_ZOLTA, WITOSA, LINDA, RUBINOLA, RETINA, PRIMA, FREE_REDSTAR,
        DELBARESTIVALE, DELIKATES, SANDER, RED_CHIEF, EARLY_GENEVA, GINGER_GOLD, ORION, CHAMPION,
        EARLY_GOLD, PAULA_RED, SHINSEIKI, FREEDOM, ENTERPRISE,
        PRISCILLA, WILLIAMS_PRIDE, OPAL_GOLD, DELGADO, SUPREMA,
        RED_JONAPRINCE, JONARED, SUPREMA_GOLD, MUTSU_CRISPY,
        MORGANA, BONITA, KIKU, SWEETANGO, COSMIC_CRISP,
        EVELINA, NOVA_MAC, GENEVA_EARLY, BELGICA, CELINA,

        OTHER
    }



    public enum PearVariety {
        KONFERENCJA, WILLIAMS, BOSC, CLAPPS_FAVORITE, ANJOU, COMICE, SANDRA, LUTY, KOSZTELA, SERENA,
        KARMEN, ALEXANDRIA, HOSUI, SECKEL, FLORIDA_PRINCESS,
        LUCAS, MOLTKE, FAWORYTKA, PARYZANKA, SUCZY_WOJTEK,
        ABATE_FETEL, HARROW_SWEET, HARROW_GOLD, CONCORDE,
        BUTIRA_HARDY, MARGUERITE_MARILLAT, FLEMISH_BEAUTY,
        DOYENNE_DU_COMICE_RED, TRIOMPHE_DE_VIENNE, PACKHAMS_TRIUMPH,
        BEURRE_HARDENPONT, BEURRE_ALEXANDRINA, BEURRE_BOSC, ROYAL_RIVIERA, OTHER
    }


    public enum CherryVariety {
        BURLAT, STELLA, VAN, KORDIA, MORELLO, SKEENA, MERLYN, SUMMIT, LAPINS, SWEETHEART,
        NANA, DEBORA, SABINA, ALBERTINE, ERDI_BOTERMO, MONTMORENCY, NORTHSTAR, BALATON, GRIOTTE,
        LUDWIKA, OSTHEIMER, ERDI_JUBILEUM, DEBORA_LATE, OTHER
    }


    public enum SweetCherryVariety {
        SIMONA, WERA, STACATO, BING, RAINIER, BLACK_TARTARIAN, SUNBURST,
        FERROVIE, VAN, SWEET_HEART, LAPINS, KORDIA, MERLYN,
        REGINA, KALEINA, ATTIKA, SUMMIT, SAM, TECHLOVAN, SKEENA, SYLVIA,
        VALINA, TAMARA, VERA_LATE, PRIMA_GIANT, EARLY_LORY, EARLY_STAR,
        FRISCO, SANTINA, GRACE_STAR, SWEET_AREKO, BIGAREAU, BLACK_GOLD, WHITE_HEART, RONALDA,
        MARMOLADA, GIORGIA, PRIME_GIANT, RED_GIANT, SWEET_STEFANI, RED_RONA, BIG_STAR, TARDI_BERTI,
        SWEET_SARAH, DURONI, MONTANA, CANADA_GIANT, OTHER
    }



    public enum PlumVariety {
        WEGIERSKA, RENKLODA, ELENA, PRESIDENT, CECYLIA, ANGELINA, OPAL,
        HUNGARIAN, BLUEFRE, VIOLET, DAMSON, VICTORIA, MIRABELLE, SANTA_ROSA,
        STANLEY, EMPRESS, JOJO, HERMAN, KATINKA, KATANA, PRESIDENT_LATE,
        HANITA, TOPTASTE, TOPGIGANT, TOPEND_PLUS, TOPHIT, TIPALA,
        CZARNA_WEGIERSKA, AMERS, FRUITION, CATALINA, BEAUTY, EARLY_GOLDEN,
        BLACK_AMBER, SHIRO, METHLEY, BAVAY_GREEN_GAGE, OPAL_RED, TULSKAYA_BLACK, GRANIT, BLUE_DELICIOUS,
        IMPERIAL_GAGE, EDWARD_GAGE, ALPINE, KYOTO, SHIRO_GOLD, LARRY_ANN, ANGELENO, ROYAL_ROSA,
        LUPINE_BLUE, BLUE_TITAN, MIRABELLE_NANCY, PRUNE_DAGENS, OTHER
    }



    public enum RaspberryVariety {
        POLKA, GLEN_AMPLE, HERITAGE, AUTUMN_BLOSSOM, TULAMEEN, NOVA, LATHAM,
        MEGASPLASH, AUTUMN_GOLD, KILLARNY, POLANA,
        LASZKA, ENROSADIRA, MAPEMA, IMARA, KWAZAR, JOAN_J, JOANNE, VINTAGE,
        PRIMOCANE, DELNIWA, ERIKA, VETEK, OCTAVIA, GLEN_FYNE, GLEN_MOY,
        SUGANA, MALLING_JUNO, MALLING_JOY, MALLING_MINERVA, BLACK_JEWEL,
        BRISTOL, ROYALTY, ANSETA, KWANZA, OTHER
    }

    public enum StrawberryVariety {
        HONEOYE, ELSANTA, ALBA, CLERY, APRICA, FLORENCE, SONATA, ROXANA,
        RUMBA, MARMOLADA, SENGA_SENGANA, POLKA, MALWINA, KENT, ASIA,
        PORTOLA, SAN_ANDREAS, MONTEREY, VIBRANT, DARSELECT, JIVE,
        ELEGANCE, MAGNUS, LUBAWA, WENDY, FAITH, SALSA, FIGARO,
        OTHER
    }

    public enum BlackCurrantVariety {
        TITANIA, BEN_LOMOND, BEN_NEVIS, TISEL, TIBEN, RUTIS, ORES,
        GAUSHA, GOLUBKA, RUBEN, OJCZYSTA, PORTIUS, BIG_BLACK, FERTODI,
        OTHER
    }

    public enum RedCurrantVariety {
        JONKER_VAN_TETS, ROVADA, HOLLANDE, LONDON_MARKET, ROLLAN,
        RED_LAKE, ROSALINDA, DETVAN, VYTIS, LUNA, ROSA, HOLLAND,
        OTHER
    }

    public enum GooseberryVariety {
        INVICTA, HINNONMAKI_RED, HINNONMAKI_YELLOW, ROLONDA, CAPTIVATOR,
        MAYDUKE, PAX, DARROWS, POORMAN, JEWEL, SPINEFREE, OTHER
    }

    public enum BlueberryVariety {
        DUKE, BLUECROP, CHANDLER, LEGACY, SPARTAN, PATRIOT, AURORA,
        DRAPER, RAZZ, DARROW, NORTHLAND, LIBERTY, BILOXI, MISTY,
        OCHLOCKONEE, BRIGITTA, BLUEJAY, BLUEGOLD, OTHER
    }

    public enum BlackberryVariety {
        LOCH_NESS, THORNFREE, NAVAHO, TRIPLE_CROWN, BLACK_SATIN,
        CHESTER, CAUMILLER, APACHE, OSAGE, ARAPAHO, NATCHEZ, PRIME_ARK,
        OTHER
    }

    public enum AroniaVariety {
        NERO, VIKING, GALICJANKA, HUGIN, ARONIA_MOSCOW, ARONIA_MORAVIA,
        KARPATIA, OTHER
    }


}