package fruit.farm.management.entity;

public enum ProfitType {

    SPRZEDAZ_JABLEK,
    SPRZEDAZ_GRUSZEK,
    SPRZEDAZ_WISNI,
    SPRZEDAZ_CZERESNI,
    SPRZEDAZ_SLIW,
    SPRZEDAZ_MALIN,
    SPRZEDAZ_TRUSKAWEK,
    SPRZEDAZ_PORZECZEK_CZARNYCH,
    SPRZEDAZ_PORZECZEK_CZERWONYCH,
    SPRZEDAZ_AGRESTU,
    SPRZEDAZ_BOROWEK,
    SPRZEDAZ_JEZYN,
    SPRZEDAZ_ARONII,
    SPRZEDAZ_INNYCH_OWOCOW,
    SPRZEDAZ_HURTOWA,
    SPRZEDAZ_DETALICZNA,
    EKSPORT,
    SPRZEDAZ_ONLINE,

    SUBSYDIA,
    ODSZKODOWANIE,
    SPRZEDAZ_SPRZETU,
    USLUGI,
    CZYNSZ,
    INNE
}